services:
    fastapi:
        image: fastapi:latest
        ports:
            - "8000:8000"
        networks:
            myapp:
            
    streamlit:
        image: streamlit:latest
        ports:
            - "8501:8501"
        networks:
            myapp:
        depends_on:
            - fastapi
        environment:
            API_URL: http://fastapi:8000
            
            
networks:
    myapp:
        driver: bridge
        