name: MLOps CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
 

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run tests
#        run: |
#          pytest tests/
      - name: Run Data Processing
        run: |
          python src/data/run_processing.py

      - name: Train the Model
        run: |
          python src/models/train_model.py \
          --config configs/model_config.yaml \
          --data data/processed/cleaned_snp_data.csv \
          --models_dir models/trained \
          --mlflow-tracking-uri http://localhost:5555

