name: MLOps CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
 

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run tests
#        run: |
#          pytest tests/
      - name: Run Data Processing
        run: |
          python src/data/run_processing.py

      
      - name: Setup MLFlow 
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d --name mlflow-server -p 5555:5000 ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Train the Model
        run: |
          python src/models/train_model.py \
          --config config/model_config.yaml \
          --data data/processed/cleaned_snp_data.csv \
          --models_dir models/  \
          --mlflow_tracking_uri http://localhost:5555


      - name: Cleaning up MLflow 
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}


      - name: Set up Docker Buildx
        uses: docker/setup-bulidx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: zahedgolabi/fastapi:{{github.sha}}
          context: "."
          file: "dockerfile"

           

